In [1]:
import pandas as pd
import glob as glob
import xmltodict
import numpy as np

## Test CODE

In [2]:
excel_data_paths = glob.glob('data_source/**/*.xlsx', recursive=True)

for path in excel_data_paths:
    if('questionstats' in path):
        print(path)

data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (ខេត្តព្រះវិហា ឧត្តមានជ័យ សៀមរាប-៧)/Exam-PVH-UDM-7-ប្រឡង-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់/DSE-EXAM-ERA5-Senate-វិញ្ញាសាប្រឡង-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ខេត្តកែប-កំពត-ព្រះសីហនុ-កោះកុង/questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (Senate-City Hall & Moeys)/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់(2022)-ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ខេត្តបន្ទាយមានជ័យ -​ ខេត្តបាត់ដំបង -ពោធិ៍សាត់ -កំពង់ឆ្នាំង-ប៉ៃលិន (DSE-09)/questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ នៃក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍-8/ប្រឡងវិញ្ញាបនបត្រក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍-ប្រឡងវិញ្ញាបនបត្រ DSE (ក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍-8)-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (CADT)/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (CADT-1)-Exam-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (ខេត្ត-6)/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់(2022)-ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់-questionstats.xlsx

In [3]:
df_q_state = pd.read_excel('./data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់/DSE-EXAM-ERA5-Senate-វិញ្ញាសាប្រឡង-questionstats.xlsx', sheet_name=1)
df_q_state.columns = df_q_state.columns.str.lower()

facility_index_rate = []
for facility_index in df_q_state['facility index']:
    facility_index = facility_index[:-1]
    # print(facility_index)
    facility_index_rate.append(float(facility_index))

df_q_state['facility index'] = facility_index_rate

df_q_state.loc[df_q_state['facility index'] <= float(60), 'label_facility_index'] = 'L3'
df_q_state.loc[(df_q_state['facility index'] > float(60)) & (df_q_state['facility index'] <= float(80)), 'label_facility_index'] = 'L2'
df_q_state.loc[(df_q_state['facility index'] > float(80)) & (df_q_state['facility index'] <= float(100)), 'label_facility_index'] = 'L1'

# df_q_state.head()

In [4]:
df = df_q_state
df['name'] = ''
df

,q#,question type,question name,attempts,facility index,standard deviation,random guess score,intended weight,effective weight,discrimination index,discriminative efficiency,label_facility_index,name
0,1.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,58.81,49.10%,NaN,1.00%,0.96%,24.23%,29.61%,L3,
1,2.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,57.99,49.05%,NaN,1.00%,0.98%,25.71%,31.29%,L3,
2,3.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,54.70,49.33%,NaN,1.00%,1.01%,27.04%,32.48%,L3,
3,4.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,57.76,48.90%,NaN,1.00%,1.05%,29.75%,36.01%,L3,
4,5.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,59.10,48.67%,NaN,1.00%,0.95%,23.87%,28.98%,L3,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,100.33,Multiple choice,អភិបាលកិច្ចឌីជីថល-003,50,26.33,38.26%,NaN,1.00%,NaN,39.91%,46.92%,L3,
427,100.34,Multiple choice,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-001,195,34.44,33.29%,NaN,1.00%,NaN,18.96%,20.23%,L3,
428,100.35,Multiple choice,សន្តិសុខឌីជីថល-001,205,64.80,42.94%,NaN,1.00%,NaN,46.26%,53.82%,L2,
429,100.36,Multiple choice,រដ្ឋាភិបាលឌីជីថល-002,241,11.83,19.89%,NaN,1.00%,NaN,31.32%,40.99%,L3,
430,100.37,Multiple choice,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-002,216,14.81,26.79%,NaN,1.00%,NaN,31.86%,41.30%,L3,

In [5]:
names = []
for name in df['question name']:
    if('Random' in name):
        names.append('')
    else:
        names.append(name)

# names

df['name'] = names
df

,q#,question type,question name,attempts,facility index,standard deviation,random guess score,intended weight,effective weight,discrimination index,discriminative efficiency,label_facility_index,name
0,1.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,58.81,49.10%,NaN,1.00%,0.96%,24.23%,29.61%,L3,
1,2.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,57.99,49.05%,NaN,1.00%,0.98%,25.71%,31.29%,L3,
2,3.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,54.70,49.33%,NaN,1.00%,1.01%,27.04%,32.48%,L3,
3,4.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,57.76,48.90%,NaN,1.00%,1.05%,29.75%,36.01%,L3,
4,5.00,Random,Random (០១​. កុំព្យូទ័រចាំបាច់ and subcategori...,670,59.10,48.67%,NaN,1.00%,0.95%,23.87%,28.98%,L3,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,100.33,Multiple choice,អភិបាលកិច្ចឌីជីថល-003,50,26.33,38.26%,NaN,1.00%,NaN,39.91%,46.92%,L3,អភិបាលកិច្ចឌីជីថល-003
427,100.34,Multiple choice,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-001,195,34.44,33.29%,NaN,1.00%,NaN,18.96%,20.23%,L3,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-001
428,100.35,Multiple choice,សន្តិសុខឌីជីថល-001,205,64.80,42.94%,NaN,1.00%,NaN,46.26%,53.82%,L2,សន្តិសុខឌីជីថល-001
429,100.36,Multiple choice,រដ្ឋាភិបាលឌីជីថល-002,241,11.83,19.89%,NaN,1.00%,NaN,31.32%,40.99%,L3,រដ្ឋាភិបាលឌីជីថល-002
430,100.37,Multiple choice,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-002,216,14.81,26.79%,NaN,1.00%,NaN,31.86%,41.30%,L3,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-002

In [6]:
df = df[['name','attempts','facility index', 'label_facility_index']]
df = df[df['name'] != '']
df

,name,attempts,facility index,label_facility_index
12,hardware component-001,160,69.38,L2
13,Security-001,221,83.71,L1
14,Virus-001,225,76.44,L2
15,CPU-002,221,59.28,L3
16,Green IT-003,146,41.78,L3
...,...,...,...,...
426,អភិបាលកិច្ចឌីជីថល-003,50,26.33,L3
427,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-001,195,34.44,L3
428,សន្តិសុខឌីជីថល-001,205,64.80,L2
429,រដ្ឋាភិបាលឌីជីថល-002,241,11.83,L3
430,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-002,216,14.81,L3

In [7]:
df.groupby(df['name'])['attempts']

In [8]:
df

,name,attempts,facility index,label_facility_index
12,hardware component-001,160,69.38,L2
13,Security-001,221,83.71,L1
14,Virus-001,225,76.44,L2
15,CPU-002,221,59.28,L3
16,Green IT-003,146,41.78,L3
...,...,...,...,...
426,អភិបាលកិច្ចឌីជីថល-003,50,26.33,L3
427,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-001,195,34.44,L3
428,សន្តិសុខឌីជីថល-001,205,64.80,L2
429,រដ្ឋាភិបាលឌីជីថល-002,241,11.83,L3
430,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-002,216,14.81,L3

## Combine QuestionStats

In [9]:
excel_data_paths = glob.glob('data_source/**/*.xlsx', recursive=True)


combined_df = pd.DataFrame()
tmp_combined_df = pd.DataFrame()
is_first_loop = True

for path in excel_data_paths:
    if('questionstats' in path):
        print(path)

        df_q_state = pd.read_excel(path, sheet_name=1)
        df_q_state.columns = df_q_state.columns.str.lower()

        facility_index_rate = []
        for facility_index in df_q_state['facility index']:
            facility_index = facility_index[:-1]
            # print(facility_index)
            facility_index_rate.append(float(facility_index))

        df_q_state['facility index'] = facility_index_rate

        df_q_state.loc[df_q_state['facility index'] <= float(60), 'label_facility_index'] = 'L3'
        df_q_state.loc[(df_q_state['facility index'] > float(60)) & (df_q_state['facility index'] <= float(80)), 'label_facility_index'] = 'L2'
        df_q_state.loc[(df_q_state['facility index'] > float(80)) & (df_q_state['facility index'] <= float(100)), 'label_facility_index'] = 'L1'

        # df = df_q_state
        df_q_state['name'] = ''

        names = []
        for name in df_q_state['question name']:
            if('Random' in name):
                names.append('')
            else:
                names.append(name)
        
        df_q_state['name'] = names

        df_q_state = df_q_state[['name','attempts','facility index', 'label_facility_index']]
        df_q_state = df_q_state[df_q_state['name'] != '']
        # print(df_q_state)

        if(is_first_loop):
            is_first_loop = False
            tmp_combined_df = df_q_state
            combined_df = tmp_combined_df
        else:
            next_df = df_q_state
            combined_df = pd.concat([combined_df, next_df], ignore_index=True)

# combined_df.to_excel('combined_question_stats.xlsx')
combined_df['name'].nunique()

data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (ខេត្តព្រះវិហា ឧត្តមានជ័យ សៀមរាប-៧)/Exam-PVH-UDM-7-ប្រឡង-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់/DSE-EXAM-ERA5-Senate-វិញ្ញាសាប្រឡង-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ខេត្តកែប-កំពត-ព្រះសីហនុ-កោះកុង/questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (Senate-City Hall & Moeys)/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់(2022)-ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ខេត្តបន្ទាយមានជ័យ -​ ខេត្តបាត់ដំបង -ពោធិ៍សាត់ -កំពង់ឆ្នាំង-ប៉ៃលិន (DSE-09)/questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ នៃក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍-8/ប្រឡងវិញ្ញាបនបត្រក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍-ប្រឡងវិញ្ញាបនបត្រ DSE (ក្រសួងប្រៃសណីយ៍ និងទូរគមនាគមន៍-8)-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (CADT)/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (CADT-1)-Exam-questionstats.xlsx
data_source/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់ (ខេត្ត-6)/ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់(2022)-ប្រឡងវិញ្ញាបនបត្រជំនាញឌីជីថលចាំបាច់-questionstats.xlsx

347

In [10]:
combined_df

,name,attempts,facility index,label_facility_index
0,hardware component-001,52,76.92,L2
1,Security-001,58,77.59,L2
2,Virus-001,58,82.76,L1
3,CPU-002,60,63.33,L2
4,Green IT-003,53,50.94,L3
...,...,...,...,...
2670,អភិបាលកិច្ចឌីជីថល-003,11,22.73,L3
2671,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-001,55,24.55,L3
2672,សន្តិសុខឌីជីថល-001,46,63.04,L2
2673,រដ្ឋាភិបាលឌីជីថល-002,65,10.77,L3
2674,ហេដ្ឋារចនាសម្ព័ន្ធឌីជីថល-002,49,10.20,L3

In [11]:
uniques_name = combined_df['name'].unique()

final_df_q_stats = pd.DataFrame()
tmp_combined_df = pd.DataFrame()
is_first_loop = True

for name in uniques_name:
    each_name_df = combined_df[combined_df['name'] == name]
    # print(each_name_df) #TODO

    value_count = each_name_df['label_facility_index'].value_counts(normalize=True)

    attempt = each_name_df['attempts'].sum()
    # print(attempt)

    correct_rate = each_name_df['facility index'].mean()
    # print(correct_rate)

    if(correct_rate <= float(60)):
        label = 'L3'
    elif(correct_rate > float(60) and correct_rate <= (80)):
        label = 'L2'
    elif(correct_rate > float(80) and correct_rate <= float(100)):
        label = 'L1'

    data = [[name,
             attempt,
             correct_rate,
             label]]

    if(is_first_loop):
        is_first_loop = False
        tmp_combined_df = pd.DataFrame(data, columns=['name',
                                                      'attempt',
                                                      'correct_rate',
                                                      'level'])
        final_df_q_stats = tmp_combined_df
    else:
        next_df = pd.DataFrame(data, columns=['name', 
                                              'attempt',
                                              'correct_rate',
                                              'level'])
        final_df_q_stats = pd.concat([final_df_q_stats, next_df], ignore_index=True)
        
    # break

# final_df_q_stats.to_excel('final_question_stats_with_label.xlsx')

final_df_q_stats

                                      name  attempt  correct_rate level
0                   hardware component-001      519      76.39250    L2
1                             Security-001      730      79.92375    L2
2                                Virus-001      663      76.18875    L2
3                                  CPU-002      653      53.48500    L3
4                             Green IT-003      542      53.04875    L3
..                                     ...      ...           ...   ...
342                      Question-Type-002       14      57.14000    L3
343                      Question-Type-001       19      21.05000    L3
344                    Double Negative-003       11      90.91000    L1
345  ការអនុវត្តន៍ការធ្វើការជាក្រុមតាមអនឡាញ        3      73.33000    L2
346                           location-001        1     100.00000    L1

[347 rows x 4 columns]

## Combine Question Pools

In [12]:
xml = sorted(glob.glob('./data_source_xml/*.xml'))

combined_df_q_pool = pd.DataFrame()
tmp_combined_df_q_pool = pd.DataFrame()
is_first_loop = True

for path in xml:
    with open(path) as fd:
        doc = xmltodict.parse(fd.read())

    df_xml1 = pd.DataFrame(doc['quiz'])
    # df_xml1.head(3)

    columns_name = df_xml1['question'][0].keys()

    data = []
    subject_xml1_df = pd.DataFrame(data, columns=columns_name)

    for i in range(len(df_xml1)):
        subject_xml1_df.loc[i] = df_xml1['question'][i]

    names = []
    for i in range(len(subject_xml1_df)):
        names.append(subject_xml1_df['name'][i]['text'])

    subject_xml1_df['name'] = names
    # subject_xml1_df.head(3)

    level = []
    q_type = []
    for i in range(len(subject_xml1_df)):
        
        if(pd.isna(subject_xml1_df['tags'][i])):
            level.append('pending')
            q_type.append('pending')
        else:
            level_object = str(subject_xml1_df['tags'][i]['tag'])

            if('l1' in level_object or 'L1' in level_object):
                level.append('L1')
            elif('l2' in level_object or 'L2' in level_object):
                level.append('L2')
            elif('l3' in level_object or 'L3' in level_object):
                level.append('L3')
            elif('pending' in level_object or 'Pending' in level_object):
                level.append('pending')
            else:
                level.append('reviewing')
            
            if('exam' in level_object or 'Exam' in level_object):
                q_type.append('exam')
            elif('quiz' in level_object or 'Quiz' in level_object):
                q_type.append('quiz')
            elif('pretest' in level_object or 'Pretest' in level_object):
                q_type.append('pretest')
            elif('pending' in level_object or 'Pending' in level_object):
                q_type.append('pending')
            elif('review' in level_object or 'Review' in level_object):
                q_type.append('review')
            else:
                q_type.append(None)

    subject_xml1_df['level'] = level
    subject_xml1_df['q_type'] = q_type
    subject_xml1_df['subject_th'] = path.split('/')[-1].split('.')[0]
    
    if(is_first_loop):
        is_first_loop = False
        tmp_combined_df_q_pool = subject_xml1_df[['name', 'level', 'q_type','subject_th']]
        combined_df_q_pool = tmp_combined_df_q_pool
    else:
        next_df = subject_xml1_df[['name', 'level', 'q_type','subject_th']]
        combined_df_q_pool = pd.concat([combined_df_q_pool, next_df], ignore_index=True)
        
combined_df_q_pool.to_excel('./data_source_xml/combined_question_pool_total.xlsx')

question_with_label_only_df = combined_df_q_pool[combined_df_q_pool['level'].isin(['L1', 'L2', 'L3'])]
question_with_label_only_df.to_excel('./data_source_xml/question_pool_level_only.xlsx')

print("Combined dataset of question pools!!!")
print("Saved files to folders!")

print("Number of Total Question:", len(combined_df_q_pool))
print("Number of question with Label:", len(combined_df_q_pool[combined_df_q_pool['level'].isin(['L1', 'L2', 'L3'])]))

Combined dataset of question pools!!!
Saved files to folders!
Number of Total Question: 690
Number of question with Label: 617

## Operation - Create Final Recommend Question Level Status

In [13]:
final_df_q_stats

                                      name  attempt  correct_rate level
0                   hardware component-001      519      76.39250    L2
1                             Security-001      730      79.92375    L2
2                                Virus-001      663      76.18875    L2
3                                  CPU-002      653      53.48500    L3
4                             Green IT-003      542      53.04875    L3
..                                     ...      ...           ...   ...
342                      Question-Type-002       14      57.14000    L3
343                      Question-Type-001       19      21.05000    L3
344                    Double Negative-003       11      90.91000    L1
345  ការអនុវត្តន៍ការធ្វើការជាក្រុមតាមអនឡាញ        3      73.33000    L2
346                           location-001        1     100.00000    L1

[347 rows x 4 columns]

In [14]:
question_with_label_only_df['attempt'] = None
question_with_label_only_df['correct_rate'] = None
question_with_label_only_df['recommended_level'] = None
question_with_label_only_df

/var/folders/dt/90w7dnxx5xzfd7px48yrrpt00000gn/T/ipykernel_9874/4128611128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  question_with_label_only_df['attempt'] = None
/var/folders/dt/90w7dnxx5xzfd7px48yrrpt00000gn/T/ipykernel_9874/4128611128.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  question_with_label_only_df['correct_rate'] = None
/var/folders/dt/90w7dnxx5xzfd7px48yrrpt00000gn/T/ipykernel_9874/4128611128.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  question_with_label_only_df['recommended_level'] = None

,name,level,q_type,subject_th,attempt,correct_rate,recommended_level
0,Mainboard-003,L2,exam,1,None,None,None
1,jc-q18,L1,exam,1,None,None,None
2,File Extensions-001,L3,exam,1,None,None,None
3,Hardware-001,L2,exam,1,None,None,None
4,Speed Unit-001,L2,exam,1,None,None,None
...,...,...,...,...,...,...,...
685,Tools,L2,None,9,None,None,None
686,col-help-workplace,L1,quiz,9,None,None,None
687,Document Sharing,L2,quiz,9,None,None,None
688,Feature-010,L1,pretest,9,None,None,None
689,Google Docs-010,L1,pretest,9,None,None,None

In [15]:
for name in final_df_q_stats['name'].tolist():

    # print(final_df_q_stats[final_df_q_stats['name'] == name])
    # print(question_with_label_only_df[question_with_label_only_df['name'] == name])

    if(name in question_with_label_only_df['name'].tolist()):

        attempt = final_df_q_stats.loc[final_df_q_stats['name'] == name, 'attempt'].values[0]
        correct_rate = final_df_q_stats.loc[final_df_q_stats['name'] == name, 'correct_rate'].values[0]
        recommended_level = final_df_q_stats.loc[final_df_q_stats['name'] == name, 'level'].values[0]

        question_with_label_only_df.loc[question_with_label_only_df['name'] == name, 'attempt' ] = attempt
        question_with_label_only_df.loc[question_with_label_only_df['name'] == name, 'correct_rate' ] = correct_rate
        question_with_label_only_df.loc[question_with_label_only_df['name'] == name, 'recommended_level' ] = recommended_level

        level = final_df_q_stats.loc[final_df_q_stats['name'] == name, 'level'].values[0]
        question_with_label_only_df.loc[question_with_label_only_df['name'] == name, 'recommended_level' ] = level
        
    else:
        question_with_label_only_df.loc[question_with_label_only_df['name'] == name, 'attempt' ] = None
        question_with_label_only_df.loc[question_with_label_only_df['name'] == name, 'correct_rate' ] = None
        question_with_label_only_df.loc[question_with_label_only_df['name'] == name, 'recommended_level' ] = None
    
    # break

In [16]:
question_with_label_only_df

,name,level,q_type,subject_th,attempt,correct_rate,recommended_level
0,Mainboard-003,L2,exam,1,633,32.5625,L3
1,jc-q18,L1,exam,1,508,41.20875,L3
2,File Extensions-001,L3,exam,1,741,75.35,L2
3,Hardware-001,L2,exam,1,697,58.7025,L3
4,Speed Unit-001,L2,exam,1,673,45.69875,L3
...,...,...,...,...,...,...,...
685,Tools,L2,None,9,None,None,None
686,col-help-workplace,L1,quiz,9,None,None,None
687,Document Sharing,L2,quiz,9,None,None,None
688,Feature-010,L1,pretest,9,None,None,None
689,Google Docs-010,L1,pretest,9,None,None,None

In [17]:
question_with_label_only_df.to_excel('./question_difficulty_level_result/recommended_question_level_all.xlsx', index=False)

In [18]:
exam_only = question_with_label_only_df[question_with_label_only_df['q_type'] == 'exam']
pending_only = question_with_label_only_df[question_with_label_only_df['q_type'] == 'pending']
review_only = question_with_label_only_df[question_with_label_only_df['q_type'] == 'review']

exam_only.to_excel('./question_difficulty_level_result/recommended_question_level_exam_only.xlsx', index=False)
pending_only.to_excel('./question_difficulty_level_result/recommended_question_level_pending_only.xlsx', index=False)
review_only.to_excel('./question_difficulty_level_result/recommended_question_level_review_only.xlsx', index=False)

In [19]:
from collections import Counter
print(Counter(np.array(exam_only.level)))
print(exam_only.shape[0])

Counter({'L2': 138, 'L1': 114, 'L3': 79})
331

In [20]:
print(Counter(np.array(exam_only['recommended_level'])))
print(exam_only.shape[0])

Counter({'L3': 205, 'L2': 92, 'L1': 33, None: 1})
331

In [21]:
subjects = question_with_label_only_df['subject_th'].unique()

for subj in subjects:
    df = question_with_label_only_df[question_with_label_only_df['subject_th'] == subj]
    save_path = './question_difficulty_level_result/'+str(subj)+'.xlsx'
    df.to_excel(save_path, index=False)
    print("Saved to " + save_path)

Saved to ./question_difficulty_level_result/1.xlsx
Saved to ./question_difficulty_level_result/10.xlsx
Saved to ./question_difficulty_level_result/11.xlsx
Saved to ./question_difficulty_level_result/12.xlsx
Saved to ./question_difficulty_level_result/2.xlsx
Saved to ./question_difficulty_level_result/3.xlsx
Saved to ./question_difficulty_level_result/4.xlsx
Saved to ./question_difficulty_level_result/5.xlsx
Saved to ./question_difficulty_level_result/6.xlsx
Saved to ./question_difficulty_level_result/7.xlsx
Saved to ./question_difficulty_level_result/8.xlsx
Saved to ./question_difficulty_level_result/9.xlsx